import { useMemo } from "react"
import { Download, Printer } from "lucide-react"
import { Button } from "@/components/ui/Button"
import { useNatalChart, useUser } from "@/context/UserContext"
import { NorthIndianChart } from "@/components/kundli/NorthIndianChart"
import { detectYogas, formatShortDate } from "@/lib/vedic"
import { CosmicField } from "@/components/sky/CosmicField"
import { useI18n } from "@/lib/i18n"

export function Kundli() {
  const { user } = useUser()
  const { t } = useI18n()
  const natal = useNatalChart()
  const yogas = useMemo(() => detectYogas(natal).filter((y) => y.isActive), [natal])

  const handlePrint = () => window.print()

  const handleDownload = () => {
    const rows = natal.bodies
      .map(
        (b) =>
          `<tr><td>${b.name}</td><td>${b.sign} ${b.degreeLabel}</td><td>${b.house}</td><td>${b.nakshatra} p${b.pada}</td><td>${b.dignity}</td></tr>`
      )
      .join("")
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${user.name} — Kundli</title>
      <style>body{font-family:Georgia,serif;padding:32px;color:#111}h1{margin:0}table{border-collapse:collapse;width:100%;margin-top:16px}td,th{border:1px solid #222;padding:6px 8px;font-size:12px;text-align:left}th{background:#111;color:#fff}</style>
      </head><body>
      <h1>${user.name} — D1 Kundli (Lahiri)</h1>
      <p>Born ${user.dob} ${user.timeOfBirth} · ${natal.placeName}<br/>
      Sun ${natal.sunSign} · Moon ${natal.moonSign} ${natal.moonNakshatra} p${natal.moonPada} · Lagna ${natal.lagnaSign}<br/>
      ${natal.dasha.label} · ${formatShortDate(natal.dasha.maha.start)} – ${formatShortDate(natal.dasha.maha.end)}</p>
      <table><thead><tr><th>Graha</th><th>Rashi / degree</th><th>House</th><th>Nakshatra</th><th>Dignity</th></tr></thead><tbody>${rows}</tbody></table>
      <p style="margin-top:24px;font-size:11px;color:#555">Generated by AstroLive · Sidereal / Lahiri ayanamsa ${natal.ayanamsa.toFixed(2)}° · Not a replacement for a living jyotishi.</p>
      </body></html>`
    const blob = new Blob([html], { type: "text/html" })
    const a = document.createElement("a")
    a.href = URL.createObjectURL(blob)
    a.download = `${user.name.replace(/\s+/g, "-")}-kundli.html`
    a.click()
  }

  const facts: [string, string][] = [
    ["Sun", natal.sunSign],
    ["Moon", natal.moonSign],
    ["Nakshatra", `${natal.moonNakshatra} p${natal.moonPada}`],
    ["Lagna", natal.lagnaSign],
    ["Maha dasha", natal.dasha.maha.lord],
    ["Antar dasha", natal.dasha.antar.lord],
  ]

  return (
    <div className="relative">
      <CosmicField density={24} />
      <div className="relative page-container max-w-5xl pb-28">
        <p className="text-[12px] uppercase tracking-[0.16em] text-zinc-500">{t("freeKundli")}</p>
        <h1 className="font-display text-4xl sm:text-6xl text-zinc-50 mt-2 leading-[0.95]">{t("chartDrawn")}</h1>
        <p className="mt-4 text-[15px] text-zinc-400 max-w-lg leading-relaxed">
          {user.name} · {user.dob} · {user.timeOfBirth} · {natal.placeName} · Lahiri {natal.ayanamsa.toFixed(2)}°
        </p>
        <div className="mt-6 flex flex-wrap gap-2 print:hidden">
          <Button variant="outline" size="sm" onClick={handlePrint}>
            <Printer className="w-3.5 h-3.5" /> {t("printPdf")}
          </Button>
          <Button size="sm" onClick={handleDownload}>
            <Download className="w-3.5 h-3.5" /> {t("download")}
          </Button>
        </div>

        <section className="mt-14 grid lg:grid-cols-12 gap-12 items-start">
          <div className="lg:col-span-5">
            <NorthIndianChart natal={natal} />
            <p className="text-[12px] text-zinc-500 mt-3">
              {natal.lagnaSign} lagna · {natal.moonSign} moon · {natal.dasha.label}
            </p>
          </div>
          <div className="lg:col-span-7 grid grid-cols-2 gap-x-8 gap-y-6">
            {facts.map(([k, v]) => (
              <div key={k}>
                <p className="text-[12px] uppercase tracking-[0.16em] text-zinc-500">{k}</p>
                <p className="mt-1 font-display text-2xl text-zinc-50">{v}</p>
              </div>
            ))}
          </div>
        </section>

        <p className="mt-8 text-sm text-zinc-500">
          {natal.dasha.label} · {formatShortDate(natal.dasha.maha.start)} → {formatShortDate(natal.dasha.maha.end)}
        </p>
        {yogas.length > 0 && (
          <p className="mt-2 text-sm text-zinc-400">{yogas.map((y) => y.name).join(" · ")}</p>
        )}

        <div className="mt-16 space-y-5">
          {natal.bodies.map((b) => (
            <div key={b.id} className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-1">
              <p className="font-display text-2xl text-zinc-50">
                {b.sanskrit} <span className="text-zinc-500 text-lg">{b.name}</span>
              </p>
              <p className="text-sm text-zinc-400">
                {b.sign} {b.degreeLabel} · house {b.house} · {b.nakshatra} p{b.pada} · {b.dignity}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
